name: update_steamWorkshop

on:
  push:
    # paths:
    #   - 'Mods/**'
  workflow_dispatch:


jobs:
  updateWorkshop:
    runs-on: [ubuntu-latest]
    steps:
      - name: "Workshop update"
        uses: kontu/workshop@e83f69ae0726722aabb53d9277ba0010ae173229
        with:
          path: 'Mods'
          steamAcct: ::add-mask::${{ secrets.steamAcct }}
          steamPasswd: ::add-mask::${{ secrets.steamPasswd }}
          ssfnContents: ::add-mask::${{ secrets.ssfnContents }}
          ssfnFileName: ::add-mask::${{ secrets.ssfn_file_name }}
          steamConfigVdf: ::add-mask::${{ secrets.steam_config_vdf }}