name: update_steamWorkshop

on:
  push:
    # paths:
    #   - 'Mods/**'
  workflow_dispatch:


jobs:
  updateWorkshop:
    runs-on: [ubuntu-latest]
    steps:
      - name: "Workshop update"
        uses: kontu/workshop@ac5db34f8ec3e19851b6b1b0e40fac1c430da569
        with:
          path: 'Mods'
          steamAcct: ::add-mask::${{ secrets.steamAcct }}
          steamPasswd: ::add-mask::${{ secrets.steamPasswd }}
          ssfnContents: ::add-mask::${{ secrets.ssfnContents }}
          ssfnFileName: ::add-mask::${{ secrets.ssfn_file_name }}
          steamConfigVdf: ::add-mask::${{ secrets.steam_config_vdf }}