name: update_steamWorkshop

on:
  workflow_dispatch:
  push:
    paths:
      - 'Mods/**'

jobs:
  updateWorkshop:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Workshop update"
        uses: kontu/workshop_updater@v1.0
        with:
          path: 'Mods'
          steamAcct: ${{ secrets.steamAcct }}
          steamPasswd: ${{ secrets.steamPasswd }}
          ssfnContents: ${{ secrets.ssfnContents }}
          ssfnFileName: 'ssfn1098596842295311902'
          steamConfigVdf: ${{ secrets.steam_config_vdf }}
