name: update_steamWorkshop

on:
  push:
    paths:
      - 'Mods/**'
  workflow_dispatch:


jobs:
  updateWorkshop:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }}| xargs)"
      - name: echo the changed files for kicks
        run: |
          for i in ${{ steps.getfile.outputs.files }}
          do
              echo $i
          done
      - name: "Workshop update"
        uses: kontu/workshop@1e7a5c13bb4f0a4144bee32d69c0d8a5f6b510ac
        with:
          path: 'Mods'
          steamAcct: ::add-mask::${{ secrets.steamAcct }}
          steamPasswd: ::add-mask::${{ secrets.steamPasswd }}
          files: ${{ steps.getfile.outputs.files }}