name: update_steamWorkshop

on:
  push:
    # paths:
    #   - 'Mods/**'
  workflow_dispatch:


jobs:
  updateWorkshop:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Workshop update"
        uses: kontu/workshop@latest
        with:
          path: 'Mods'
          steamAcct: ${{ secrets.steamAcct }}
          steamPasswd: ${{ secrets.steamPasswd }}
          ssfnContents: ${{ secrets.ssfnContents }}
          ssfnFileName: 'ssfn9160040175199086881'
          steamConfigVdf: ${{ secrets.steam_config_vdf }}