name: update_steamWorkshop

on:
  workflow_dispatch:
    inputs:
      modNames:
        Description: 'Full name of mod folder to upload. Eg: DraconisOres6.0'

jobs:
  updateWorkshop:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Workshop update"
        uses: kontu/workshop_updater@v1.0
        with:
          path: 'Mods'
          modNames: ${{ inputs.modNames }}
          steamAcct: ${{ secrets.steamAcct }}
          steamPasswd: ${{ secrets.steamPasswd }}
          ssfnContents: ${{ secrets.ssfnContents }}
          ssfnFileName: ${{ secrets.ssfnFileName }}'
          steamConfigVdf: ${{ secrets.steam_config_vdf }}
