name: update_steamWorkshop

on:
  push:
    # paths:
    #   - 'Mods/**'
  workflow_dispatch:


jobs:
  updateWorkshop:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Workshop update"
        uses: kontu/workshop@9bf9227a7d86fcd96502b1afb51847d64c4fdd50
        with:
          path: 'Mods'
          steamAcct: ::add-mask::${{ secrets.steamAcct }}
          steamPasswd: ::add-mask::${{ secrets.steamPasswd }}
          ssfnContents: ::add-mask::${{ secrets.ssfnContents }}
          ssfnFileName: ::add-mask::${{ secrets.ssfn_file_name }}
          steamConfigVdf: ::add-mask::${{ secrets.steam_config_vdf }}