name: update_steamWorkshop

on:
  workflow_dispatch:
    inputs:
      modNames:
        Description: 'Full name of mod vdf to upload. If uploading multiple mods, separate with a space. Eg: `DraconisDIE_Nebula.vdf` or `DraconisDIE_Nebula`'
        required: true

jobs:
  updateWorkshop:
    secrets: inherit
    uses: DraconisCluster/SE-DraconisToolsConfigs/.github/workflows/update_steam_reusable.yml@latest
    with:
      modNames: ${{ inputs.modNames }}

