name: update_steamWorkshop

on:
  push:
    paths:
      - 'Mods/**'
  workflow_dispatch:


jobs:
  updateWorkshop:
    runs-on: [ubuntu-latest]
    steps:
      - name: "Workshop update"
        uses: kontu/workshop@0ac50976818f2aa281a2b4f49233d66faaf358ca
        with:
          path: 'Mods'
          steamAcct: ::add-mask::${{ secrets.steamAcct }}
          steamPasswd: ::add-mask::${{ secrets.steamPasswd }}
          steamGuard: ::add-mask::${{ secrets.steamguard }}