name: update_steamWorkshop

on:
  workflow_dispatch:
    inputs:
      modNames:
        Description: 'Full name of mod vdf to upload. If uploading multiple mods, separate with a space. Eg: `DraconisDIE_Nebula.vdf` or `DraconisDIE_Nebula`'
        required: true

jobs:
  updateWorkshop:
    secrets: inherit
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Workshop update"
        uses: kontu/workshop_updater@latest
        with:
          modNames: ${{ inputs.modNames }}
          steamAcct: ${{ secrets.steamAcct }}
          steamPasswd: ${{ secrets.steamPasswd }}
          ssfnContents: ${{ secrets.ssfnContents }}
          ssfnFileName: ${{ secrets.ssfnFileName }}
          steamConfigVdf: ${{ secrets.steam_config_vdf }}
