name: update_steamWorkshop

on:
  push:
    # paths:
    #   - 'Mods/**'
  workflow_dispatch:


jobs:
  updateWorkshop:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Workshop update"
        uses: kontu/workshop@a7c27ce0f6ec07cf779a761ffafda06dcb118fc3
        with:
          path: 'Mods'
          steamAcct: ::add-mask::${{ secrets.steamAcct }}
          steamPasswd: ::add-mask::${{ secrets.steamPasswd }}
          ssfnContents: ::add-mask::${{ secrets.ssfnContents }}
          ssfnFileName: 'ssfn9160040175199086881'
          steamConfigVdf: ::add-mask::${{ secrets.steam_config_vdf }}